/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlunosRouteImport } from './routes/alunos'
import { Route as BancoRouteImport } from './routes/banco'
import { Route as CapturarRouteImport } from './routes/capturar'
import { Route as FundoRouteImport } from './routes/fundo'
import { Route as GoogleRouteImport } from './routes/google'
import { Route as LancamentosRouteImport } from './routes/lancamentos'
import { Route as MensalidadesRouteImport } from './routes/mensalidades'
import { Route as RecibosRouteImport } from './routes/recibos'
import { Route as SalariosRouteImport } from './routes/salarios'
import { Route as PendenciasRouteImport } from './routes/pendencias'
import { Route as AuditoriaRouteImport } from './routes/auditoria'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosRoute = AlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const BancoRoute = BancoRouteImport.update({
  id: '/banco',
  path: '/banco',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturarRoute = CapturarRouteImport.update({
  id: '/capturar',
  path: '/capturar',
  getParentRoute: () => rootRouteImport,
} as any)
const FundoRoute = FundoRouteImport.update({
  id: '/fundo',
  path: '/fundo',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleRoute = GoogleRouteImport.update({
  id: '/google',
  path: '/google',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosRoute = LancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const MensalidadesRoute = MensalidadesRouteImport.update({
  id: '/mensalidades',
  path: '/mensalidades',
  getParentRoute: () => rootRouteImport,
} as any)
const RecibosRoute = RecibosRouteImport.update({
  id: '/recibos',
  path: '/recibos',
  getParentRoute: () => rootRouteImport,
} as any)
const SalariosRoute = SalariosRouteImport.update({
  id: '/salarios',
  path: '/salarios',
  getParentRoute: () => rootRouteImport,
} as any)
const PendenciasRoute = PendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/banco': typeof BancoRoute
  '/capturar': typeof CapturarRoute
  '/fundo': typeof FundoRoute
  '/google': typeof GoogleRoute
  '/lancamentos': typeof LancamentosRoute
  '/mensalidades': typeof MensalidadesRoute
  '/recibos': typeof RecibosRoute
  '/salarios': typeof SalariosRoute
  '/pendencias': typeof PendenciasRoute
  '/auditoria': typeof AuditoriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/banco': typeof BancoRoute
  '/capturar': typeof CapturarRoute
  '/fundo': typeof FundoRoute
  '/google': typeof GoogleRoute
  '/lancamentos': typeof LancamentosRoute
  '/mensalidades': typeof MensalidadesRoute
  '/recibos': typeof RecibosRoute
  '/salarios': typeof SalariosRoute
  '/pendencias': typeof PendenciasRoute
  '/auditoria': typeof AuditoriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/banco': typeof BancoRoute
  '/capturar': typeof CapturarRoute
  '/fundo': typeof FundoRoute
  '/google': typeof GoogleRoute
  '/lancamentos': typeof LancamentosRoute
  '/mensalidades': typeof MensalidadesRoute
  '/recibos': typeof RecibosRoute
  '/salarios': typeof SalariosRoute
  '/pendencias': typeof PendenciasRoute
  '/auditoria': typeof AuditoriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alunos'
    | '/banco'
    | '/capturar'
    | '/fundo'
    | '/google'
    | '/lancamentos'
    | '/mensalidades'
    | '/recibos'
    | '/salarios'
    | '/pendencias'
    | '/auditoria'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alunos'
    | '/banco'
    | '/capturar'
    | '/fundo'
    | '/google'
    | '/lancamentos'
    | '/mensalidades'
    | '/recibos'
    | '/salarios'
    | '/pendencias'
    | '/auditoria'
  id:
    | '__root__'
    | '/'
    | '/alunos'
    | '/banco'
    | '/capturar'
    | '/fundo'
    | '/google'
    | '/lancamentos'
    | '/mensalidades'
    | '/recibos'
    | '/salarios'
    | '/pendencias'
    | '/auditoria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlunosRoute: typeof AlunosRoute
  BancoRoute: typeof BancoRoute
  CapturarRoute: typeof CapturarRoute
  FundoRoute: typeof FundoRoute
  GoogleRoute: typeof GoogleRoute
  LancamentosRoute: typeof LancamentosRoute
  MensalidadesRoute: typeof MensalidadesRoute
  RecibosRoute: typeof RecibosRoute
  SalariosRoute: typeof SalariosRoute
  PendenciasRoute: typeof PendenciasRoute
  AuditoriaRoute: typeof AuditoriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos': {
      id: '/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banco': {
      id: '/banco'
      path: '/banco'
      fullPath: '/banco'
      preLoaderRoute: typeof BancoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capturar': {
      id: '/capturar'
      path: '/capturar'
      fullPath: '/capturar'
      preLoaderRoute: typeof CapturarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundo': {
      id: '/fundo'
      path: '/fundo'
      fullPath: '/fundo'
      preLoaderRoute: typeof FundoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google': {
      id: '/google'
      path: '/google'
      fullPath: '/google'
      preLoaderRoute: typeof GoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos': {
      id: '/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof LancamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensalidades': {
      id: '/mensalidades'
      path: '/mensalidades'
      fullPath: '/mensalidades'
      preLoaderRoute: typeof MensalidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recibos': {
      id: '/recibos'
      path: '/recibos'
      fullPath: '/recibos'
      preLoaderRoute: typeof RecibosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salarios': {
      id: '/salarios'
      path: '/salarios'
      fullPath: '/salarios'
      preLoaderRoute: typeof SalariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendencias': {
      id: '/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof PendenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlunosRoute: AlunosRoute,
  BancoRoute: BancoRoute,
  CapturarRoute: CapturarRoute,
  FundoRoute: FundoRoute,
  GoogleRoute: GoogleRoute,
  LancamentosRoute: LancamentosRoute,
  MensalidadesRoute: MensalidadesRoute,
  RecibosRoute: RecibosRoute,
  SalariosRoute: SalariosRoute,
  PendenciasRoute: PendenciasRoute,
  AuditoriaRoute: AuditoriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
